INSERT INTO productos (nombre, descripcion, precio, imagen) VALUES
('Coca Cola', 'Refresco frío', 80.00, 'cocacola.jpg'),
('Doritos', 'Snack crujiente', 30.00, 'Doritos.jpg'),
('Galletas', 'Dulces y deliciosas', 10.00, 'dino.jpg'),
('Jugo', 'Bebida natural', 70.00, 'jugo.jpg'),
('Agua', 'Agua fría', 15.00, 'agua.jpg'),
('Malta', 'Bebida energética', 70.00, 'malta.jpg'),
('Aceite', 'Para cocinar', 540.00, 'aceite.jpg'),
('Pan', 'Recién horneado', 10.00, 'pan.jpg'),
('Arroz', 'Grano esencial', 925.00, 'arroz.jpg'),
('Chocolate', 'Dulce clásico', 40.00, 'chocolate.jpg'),
('Leche', 'Fresca y nutritiva', 75.00, 'leche.jpg'),
('Yogurt', 'Natural y cremoso', 180.00, 'yogurt.jpg'),
('Maní', 'Snack salado', 15.00, 'mani.jpg'),
('Cerveza', 'La más fría', 170.00, 'c.jpg'),
('Refisal', 'La mejor', 10.00, 'sal.jpg'),
('Sopita', 'La del gustico', 10.00, 'sopita.jpg'),
('Ajo', 'Ingrediente esencial', 80.00, 'ajo.jpg'),
('Cebolla', 'Ingrediente esencial', 55.00, 'cebolla.jpg'),
('Gorras', 'La mejor a tu estilo', 300.00, 'gorras.jpg'),
('Desodorante', 'Protección todo el día', 70.00, 'deso.jpg');
